before_script:
  - mkdocs build

test:
  script:
    - [ -d "docs" ]
    - find site -mindepth 1 -type f 2>/dev/null | read

deploy:
  script:
    - rsync -avz site/ senso.me:/var/www/html/senso/docs
