site_name: Senso SDK Documentation
pages:
  - Home: index.md
  - Driver Protocol: net_protocol.md
  - BLE Protocol: ble_protocol.md
  - Unity Plugin: unity.md
  - UE4 SDK: ue4.md
  - Using lighthouse: lighthouse.md
theme: readthedocs
